"""The settings a quest was approved with, and a hand edit that changes how strictly it is checked
(core/plan_settings.py, Engine.run, core/interview_update.approve_settings)."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from core import plan_settings
from core.config import Config, EngineConfig, ExecutionConfig, KnowledgeConfig, OutputConfig, ProviderConfig
from core.engine import Engine


def _cfg(tmp_path: Path, **engine) -> Config:  # noqa: ANN003
    return Config(
        topic="plan settings probe", title="plan-settings",
        provider=ProviderConfig(name="openai", model="m1"),
        engine=EngineConfig(max_iterations=1, **engine),
        execution=ExecutionConfig(sandbox="venv", timeout_s=60),
        knowledge=KnowledgeConfig(enabled=False),
        output=OutputConfig(output_dir=tmp_path / "out"),
    )


def _interview_config(quest_root: Path) -> None:
    quest_root.mkdir(parents=True, exist_ok=True)
    (quest_root / "config.yaml").write_text("# Auto-generated by Frontier Insight `python launch.py --new`.\ntopic: x\n",
                                            encoding="utf-8")


def test_differences_name_each_setting_in_plain_words(tmp_path: Path) -> None:
    before = plan_settings.settings_of(_cfg(tmp_path))
    after = plan_settings.settings_of(_cfg(tmp_path, oracle_check="warn", review_panel=["methodologist"]))
    lines = plan_settings.differences(before, after)
    assert any("what a failed reference check does (`engine.oracle_check`)" in ln and "now warn" in ln for ln in lines)
    assert any("the reviewers (`engine.review_panel`)" in ln and "now methodologist" in ln for ln in lines)
    assert plan_settings.differences(before, before) == []


def test_only_an_interview_config_is_recorded_on_its_first_start(tmp_path: Path) -> None:
    cfg = _cfg(tmp_path)
    fi = tmp_path / "q" / ".fi"
    (tmp_path / "q").mkdir()
    (tmp_path / "q" / "config.yaml").write_text("topic: written by hand\n", encoding="utf-8")
    assert plan_settings.check(tmp_path / "q", fi, cfg) == []
    assert not (fi / plan_settings.NAME).exists(), "a hand-written config was never on a confirm screen"
    _interview_config(tmp_path / "q2")
    assert plan_settings.check(tmp_path / "q2", tmp_path / "q2" / ".fi", cfg) == []
    assert (tmp_path / "q2" / ".fi" / plan_settings.NAME).is_file()


@pytest.mark.asyncio
async def test_a_hand_edit_stops_the_quest_before_anything_runs(tmp_path: Path) -> None:
    approved = _cfg(tmp_path)
    eng = Engine(approved)
    _interview_config(eng.quest_root)
    plan_settings.record(eng.fi_dir, approved)
    edited = _cfg(tmp_path, oracle_check="warn")
    eng2 = Engine(edited, resume_quest_id=eng.quest_id)
    called = {"llm": False}

    async def no_llm() -> None:
        called["llm"] = True
        raise AssertionError("nothing may run")

    eng2._connect_llm = no_llm  # type: ignore[method-assign]
    await eng2.run()
    assert not called["llm"]
    text = (eng2.quest_root / "NEXT_STEP.md").read_text(encoding="utf-8")
    assert "engine.oracle_check" in text and "approved block, now warn" in text
    assert f"--update {eng.quest_id}" in text


def test_update_approves_the_change_and_names_it(tmp_path: Path) -> None:
    from core.interview_update import approve_settings

    root = tmp_path / "q"
    _interview_config(root)
    plan_settings.record(root / ".fi", _cfg(tmp_path))
    said: list[str] = []
    changed = approve_settings(root, _cfg(tmp_path, oracle_check="warn"), say=said.append)
    assert changed and any("engine.oracle_check" in ln for ln in said)
    now = json.loads((root / ".fi" / plan_settings.NAME).read_text(encoding="utf-8"))["settings"]
    assert now["engine.oracle_check"] == "warn"
    assert plan_settings.check(root, root / ".fi", _cfg(tmp_path, oracle_check="warn")) == []
