"""The record of approved settings and the evidence gate's receipt hold only for what they were made for.

The 2026-09-26 re-audit's P0-1 and P0-3: a record of the approved settings that could not be read was written again
from the current (weaker) config, and an evidence-gate receipt made for one analysis still stood after the analysis
changed. Both are refused now.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from core import audit_log, evidence, plan_settings, receipts
from core.config import Config, EngineConfig, ExecutionConfig, KnowledgeConfig, OutputConfig, ProviderConfig
from tests.test_evidence import ON, _quest, _state

HEADER = "# Auto-generated by Frontier Insight\n"


def _cfg(tmp_path: Path, *, oracle_check: str) -> Config:
    return Config(
        topic="integrity probe", title="integrity-probe", provider=ProviderConfig(name="openai", model="m"),
        engine=EngineConfig(max_iterations=1, oracle_check=oracle_check),
        execution=ExecutionConfig(sandbox="venv", timeout_s=60), knowledge=KnowledgeConfig(enabled=False),
        output=OutputConfig(output_dir=tmp_path / "out"),
    )


def _approved(tmp_path: Path) -> tuple[Path, Path]:
    root, fi = tmp_path / "quest", tmp_path / "quest" / ".fi"
    root.mkdir(parents=True)
    (root / "config.yaml").write_text(HEADER + "topic: probe\nengine:\n  oracle_check: block\n", encoding="utf-8")
    plan_settings.record(fi, _cfg(tmp_path, oracle_check="block"), root)
    (root / "config.yaml").write_text(HEADER + "topic: probe\nengine:\n  oracle_check: warn\n", encoding="utf-8")
    return root, fi


def test_a_record_that_cannot_be_read_is_a_difference_and_is_not_written_again(tmp_path: Path) -> None:
    for broken in ("{not valid json", json.dumps({"schema": "another/v9", "settings": {}}), json.dumps({"x": 1}), ""):
        root, fi = _approved(tmp_path / str(abs(hash(broken))))
        (fi / plan_settings.NAME).write_text(broken, encoding="utf-8")
        found = plan_settings.check(root, fi, _cfg(tmp_path, oracle_check="warn"))
        assert len(found) == 1 and "cannot be read" in found[0] and "--update" in found[0], broken
        assert (fi / plan_settings.NAME).read_text(encoding="utf-8") == broken, "never rewritten from the weaker config"


def test_a_missing_record_on_a_fresh_interview_quest_is_still_recorded(tmp_path: Path) -> None:
    root, fi = tmp_path / "q", tmp_path / "q" / ".fi"
    root.mkdir()
    (root / "config.yaml").write_text(HEADER + "topic: probe\n", encoding="utf-8")
    assert plan_settings.check(root, fi, _cfg(tmp_path, oracle_check="block")) == []
    assert (fi / plan_settings.NAME).is_file()


def test_the_engine_stops_on_a_record_edited_to_match_a_weaker_config(tmp_path: Path) -> None:
    """An edit that makes the record agree with the weaker config shows only in the record's own hash, which the
    hash-chained trace holds from the approval."""
    import asyncio

    from core.engine import Engine

    cfg = _cfg(tmp_path, oracle_check="block")
    engine = Engine(cfg)
    root, fi = engine.quest_root, engine.fi_dir
    (root / "config.yaml").write_text(HEADER + "topic: probe\nengine:\n  oracle_check: block\n", encoding="utf-8")
    plan_settings.record(fi, cfg, root)
    engine.audit.append("plan_settings_recorded",
                        sha256=hashlib.sha256((fi / plan_settings.NAME).read_bytes()).hexdigest())
    # The person (or anything with write access) lowers the check in both the config and the record.
    weaker = _cfg(tmp_path, oracle_check="warn")
    (root / "config.yaml").write_text(HEADER + "topic: probe\nengine:\n  oracle_check: warn\n", encoding="utf-8")
    plan_settings.record(fi, weaker, root)
    engine.config = weaker

    stopped: list[list[str]] = []
    engine._stop_for_changed_settings = lambda changed: stopped.append(changed) or engine._collect_artifacts({})
    asyncio.run(engine.run())
    assert stopped and "was changed after it was approved" in stopped[0][0]


def test_update_records_its_approval_in_the_trace(tmp_path: Path) -> None:
    from core.interview_update import approve_settings  # what --update calls

    root, fi = _approved(tmp_path)
    trace = fi / "audit.jsonl"
    audit_log.AuditLog(trace, root.name).append("quest_started")
    approve_settings(root, _cfg(tmp_path, oracle_check="warn"))
    events = [e for e in audit_log.read(trace) if e.get("kind") == "plan_settings_recorded"]
    assert events and events[-1]["sha256"] == hashlib.sha256((fi / plan_settings.NAME).read_bytes()).hexdigest()


def test_an_evidence_gate_receipt_for_earlier_inputs_does_not_stand(tmp_path: Path) -> None:
    root = _quest(tmp_path, protocol_status="ok", oracle_status="ok")
    _status, receipt, _problem = receipts.read(root, "evidence_gate")
    assert receipt["input_hashes"]["analysis"] == receipts.sha256({})
    changed = _state(
        analysis={"headline": "changed after the receipt"},
        cross_check={"finding": "also changed"},
        evidence_assessment={"verdict": "sufficient", "status": "ok", "failure": ""},
    )
    record = evidence.assess(root, changed, settings=ON)
    assert record["status"] != "publication_ready"
    gap = next(g for g in record["gaps"] if "evidence gate judged earlier inputs" in g)
    assert "analysis" in gap and "cross_check" in gap
    # The inputs it was made for still stand.
    assert evidence.assess(root, _state(), settings=ON)["status"] == "publication_ready"


def test_a_receipt_names_each_input_that_changed() -> None:
    record = {"input_hashes": {"a": receipts.sha256(1), "b": receipts.sha256(2)}}
    assert receipts.stale_inputs(record, {"a": 1, "b": 3, "c": 4}) == ["b", "c"]


def test_fis_own_rewrite_of_the_record_is_not_taken_for_an_edit(tmp_path: Path, monkeypatch) -> None:
    """check() rewrites the record when an FI default changed (a setting the config never set): FI's own write, whose
    hash then goes into the trace; the next start goes on."""
    import asyncio

    from core.engine import Engine

    cfg = _cfg(tmp_path, oracle_check="block")
    engine = Engine(cfg)
    root, fi = engine.quest_root, engine.fi_dir
    (root / "config.yaml").write_text(HEADER + "topic: probe\n", encoding="utf-8")
    plan_settings.record(fi, cfg, root)
    engine.audit.append("plan_settings_recorded",
                        sha256=hashlib.sha256((fi / plan_settings.NAME).read_bytes()).hexdigest())
    data = json.loads((fi / plan_settings.NAME).read_text(encoding="utf-8"))
    data["settings"]["engine.max_iterations"] = 99  # an older FI's default, never set in the config
    (fi / plan_settings.NAME).write_text(json.dumps(data), encoding="utf-8")
    engine.audit.append("plan_settings_recorded",
                        sha256=hashlib.sha256((fi / plan_settings.NAME).read_bytes()).hexdigest())

    stopped: list[list[str]] = []
    engine._stop_for_changed_settings = lambda changed: stopped.append(changed) or engine._collect_artifacts({})
    monkeypatch.setattr(engine, "_preflight_paper_pdf", lambda: (_ for _ in ()).throw(SystemExit("reached the run")))
    try:
        asyncio.run(engine.run())
    except SystemExit:
        pass
    assert not stopped, stopped
    last = [e["sha256"] for e in audit_log.read(engine.audit.path) if e.get("kind") == "plan_settings_recorded"][-1]
    assert last == hashlib.sha256((fi / plan_settings.NAME).read_bytes()).hexdigest(), "FI's rewrite is in the trace"


def test_update_before_the_first_run_starts_the_trace(tmp_path: Path) -> None:
    from core.interview_update import approve_settings

    root, fi = _approved(tmp_path)
    approve_settings(root, _cfg(tmp_path, oracle_check="warn"))
    events = [e for e in audit_log.read(fi / "audit.jsonl") if e.get("kind") == "plan_settings_recorded"]
    assert len(events) == 1


def test_a_trace_edited_to_match_an_edited_record_does_not_check_out(tmp_path: Path) -> None:
    import asyncio

    from core.engine import Engine

    cfg = _cfg(tmp_path, oracle_check="block")
    engine = Engine(cfg)
    root, fi = engine.quest_root, engine.fi_dir
    (root / "config.yaml").write_text(HEADER + "topic: probe\nengine:\n  oracle_check: block\n", encoding="utf-8")
    plan_settings.record(fi, cfg, root)
    engine.audit.append("plan_settings_recorded",
                        sha256=hashlib.sha256((fi / plan_settings.NAME).read_bytes()).hexdigest())
    weaker = _cfg(tmp_path, oracle_check="warn")
    (root / "config.yaml").write_text(HEADER + "topic: probe\nengine:\n  oracle_check: warn\n", encoding="utf-8")
    plan_settings.record(fi, weaker, root)
    lines = engine.audit.path.read_text(encoding="utf-8").splitlines()
    last = json.loads(lines[-1])
    last["sha256"] = hashlib.sha256((fi / plan_settings.NAME).read_bytes()).hexdigest()
    engine.audit.path.write_text("\n".join([*lines[:-1], json.dumps(last)]) + "\n", encoding="utf-8")
    engine.config = weaker
    stopped: list[list[str]] = []
    engine._stop_for_changed_settings = lambda changed: stopped.append(changed) or engine._collect_artifacts({})
    asyncio.run(engine.run())
    assert stopped and "no longer checks out" in stopped[0][0]


def test_the_writer_trimming_the_sources_does_not_make_the_gate_receipt_stale(tmp_path: Path) -> None:
    root = _quest(tmp_path, protocol_status="ok", oracle_status="ok")
    trimmed = _state(literature=[{"metadata": {"title": "the one source the paper cites"}}])
    assert evidence.assess(root, trimmed, settings=ON)["status"] == "publication_ready"
