"""Changing the model of a quest that already ran (core/plan_settings.py MODEL_SETTINGS, Engine._take_model_change,
core/interview_update.py).

Reported: a VS Code quest ran on gpt-5.6-luna (its config.yaml's ``provider.model``); the person set claude-opus-5
there, and resuming stopped with "settings changed, approve with --update", as if a different model changed what the
result means. A model change must not stop the quest: it is used from there on, recorded (the settings record, the
audit trace, run.log) and said plainly. What a result means (rigor_profile, a check turned down, ...) still stops.
"""

from __future__ import annotations

import asyncio
import json
from pathlib import Path
from typing import Any

import pytest

from core import audit_log, plan_settings
from core.config import Config, EngineConfig, ExecutionConfig, KnowledgeConfig, OutputConfig, ProviderConfig
from core.engine import Engine

HEADER = "# Auto-generated by the Frontier Insight VSCode extension.\n"


def _cfg(tmp_path: Path, model: str = "gpt-5.6-luna", *, name: str = "openai", extra: dict | None = None,
         node_models: dict | None = None, **engine: Any) -> Config:
    return Config(
        topic="model change probe", title="model-change",
        provider=ProviderConfig(name=name, model=model, extra=extra or {}, node_models=node_models),
        engine=EngineConfig(**{"max_iterations": 1, **engine}),
        execution=ExecutionConfig(sandbox="venv", timeout_s=60),
        knowledge=KnowledgeConfig(enabled=False),
        output=OutputConfig(output_dir=tmp_path / "out"),
    )


def _write_config(quest_root: Path, model: str, node_models: dict | None = None) -> None:
    quest_root.mkdir(parents=True, exist_ok=True)
    text = HEADER + f"topic: x\nprovider:\n  name: openai\n  model: {model}\n"
    if node_models:
        text += "  node_models:\n" + "".join(f"    {k}: {v}\n" for k, v in node_models.items())
    (quest_root / "config.yaml").write_text(text, encoding="utf-8")


class _Stop(Exception):
    pass


def _skip_setup(eng: Engine) -> None:
    """Everything between the settings check and the model connection that would build a venv or read the disk."""
    async def nothing(*_a: Any, **_k: Any) -> None:
        return None

    eng._preflight_paper_pdf = lambda: None  # type: ignore[method-assign]
    eng._preflight_required_skills = nothing  # type: ignore[method-assign]
    eng._stage_example_inputs = lambda: None  # type: ignore[method-assign]
    eng._record_environment = nothing  # type: ignore[method-assign]
    eng.executor.setup = nothing  # type: ignore[method-assign]


def _made_calls(eng: Engine, model: str = "gpt-5.6-luna") -> None:
    """The quest made calls on ``model`` before (cost.jsonl is append-only, so they stay)."""
    eng.fi_dir.mkdir(parents=True, exist_ok=True)
    (eng.fi_dir / "cost.jsonl").write_text(json.dumps({"node": "ideate", "model": model}) + "\n", encoding="utf-8")


def _started(tmp_path: Path, model: str = "gpt-5.6-luna", **kw: Any) -> Engine:
    """A quest the interview wrote, started once on ``model`` (its settings recorded)."""
    cfg = _cfg(tmp_path, model, **kw)
    eng = Engine(cfg)
    _write_config(eng.quest_root, model, kw.get("node_models"))
    plan_settings.record(eng.fi_dir, cfg, eng.quest_root)
    return eng


@pytest.mark.asyncio
async def test_a_changed_model_does_not_stop_the_resume(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    first = _started(tmp_path)
    _made_calls(first)
    _write_config(first.quest_root, "claude-opus-5")
    eng = Engine(_cfg(tmp_path, "claude-opus-5"), resume_quest_id=first.quest_id)
    _skip_setup(eng)

    async def connected() -> None:
        raise _Stop

    eng._connect_llm = connected  # type: ignore[method-assign]
    with pytest.raises(_Stop):
        await eng.run()
    assert not (eng.quest_root / "NEXT_STEP.md").exists(), "a different model is not a change to approve"
    recorded = json.loads((eng.fi_dir / plan_settings.NAME).read_text(encoding="utf-8"))["settings"]
    assert recorded["provider.model"] == "claude-opus-5"
    events = audit_log.read(eng.audit.path)
    changed = [e for e in events if e.get("kind") == "model_changed"]
    assert len(changed) == 1
    assert changed[0]["changes"][0]["from"] == "gpt-5.6-luna" and changed[0]["changes"][0]["to"] == "claude-opus-5"
    # The new record's hash is in the trace, so the next start does not read it as a hand edit.
    assert [e for e in events if e.get("kind") == "plan_settings_recorded"]
    said = ("the model changes from gpt-5.6-luna to claude-opus-5 from here on; steps already done were made by "
            "gpt-5.6-luna")
    assert f"[FI] model: {said}" in capsys.readouterr().out
    assert said in (eng.fi_dir / "run.log").read_text(encoding="utf-8")

    # The next start finds nothing new: said once, not on every resume.
    again = Engine(_cfg(tmp_path, "claude-opus-5"), resume_quest_id=first.quest_id)
    _skip_setup(again)
    again._connect_llm = connected  # type: ignore[method-assign]
    with pytest.raises(_Stop):
        await again.run()
    assert len([e for e in audit_log.read(again.audit.path) if e.get("kind") == "model_changed"]) == 1
    assert not (again.quest_root / "NEXT_STEP.md").exists()


@pytest.mark.asyncio
async def test_a_setting_that_changes_what_the_result_means_still_stops(tmp_path: Path) -> None:
    first = _started(tmp_path)
    _write_config(first.quest_root, "claude-opus-5")
    with (first.quest_root / "config.yaml").open("a", encoding="utf-8") as f:
        f.write("engine:\n  oracle_check: warn\n")
    eng = Engine(_cfg(tmp_path, "claude-opus-5", oracle_check="warn"), resume_quest_id=first.quest_id)

    async def no_llm() -> None:
        raise AssertionError("nothing may run")

    eng._connect_llm = no_llm  # type: ignore[method-assign]
    await eng.run()
    text = (eng.quest_root / "NEXT_STEP.md").read_text(encoding="utf-8")
    assert "engine.oracle_check" in text
    assert "provider.model" not in text, "the model is not one of the settings that need approving"


def _research(tmp_path: Path, model: str, statistician: str) -> Config:
    return Config.model_validate({
        "topic": "model change probe", "title": "model-change", "rigor_profile": "research",
        "provider": {"name": "openai", "model": model, "node_models": {"review_panel.statistician": statistician}},
        "execution": {"sandbox": "venv", "timeout_s": 60},
        "knowledge": {"enabled": False},
        "output": {"output_dir": str(tmp_path / "out")},
    })


def _research_started(tmp_path: Path) -> Engine:
    cfg = _research(tmp_path, "gpt-5.6-luna", "gemini-3-pro")
    first = Engine(cfg)
    _write_config(first.quest_root, "gpt-5.6-luna", {"review_panel.statistician": "gemini-3-pro"})
    plan_settings.record(first.fi_dir, cfg, first.quest_root)
    _made_calls(first)
    return first


@pytest.mark.asyncio
async def test_research_quest_takes_the_model_change_and_the_paper_is_told(tmp_path: Path) -> None:
    first = _research_started(tmp_path)
    eng = Engine(_research(tmp_path, "claude-opus-5", "gemini-3-pro"), resume_quest_id=first.quest_id)
    _skip_setup(eng)

    async def connected() -> None:
        raise _Stop

    eng._connect_llm = connected  # type: ignore[method-assign]
    with pytest.raises(_Stop):
        await eng.run()
    assert not (eng.quest_root / "NEXT_STEP.md").exists()
    note = plan_settings.model_disclosure(audit_log.read(eng.audit.path))
    assert "More than one model produced this study" in note
    assert "gpt-5.6-luna for the steps before the change, claude-opus-5 after it" in note


@pytest.mark.asyncio
async def test_research_still_stops_when_the_change_puts_every_reviewer_on_one_model(tmp_path: Path) -> None:
    """Even after the panel has reviewed once (a quest at the human-review gate): the model change is taken without a
    stop, so without this every later review would run on one model unasked."""
    first = _research_started(tmp_path)
    first.audit.append("node_completed", node="review")
    eng = Engine(_research(tmp_path, "gemini-3-pro", "gemini-3-pro"), resume_quest_id=first.quest_id)

    async def no_llm() -> None:
        raise AssertionError("nothing may run")

    eng._connect_llm = no_llm  # type: ignore[method-assign]
    await eng.run()
    pause = json.loads((eng.fi_dir / "pause.json").read_text(encoding="utf-8"))
    assert pause["kind"] == "review_models"


@pytest.mark.asyncio
async def test_a_change_before_anything_ran_is_not_disclosed(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    """The first start failed before any step (an unknown model name, a quota): nothing was made on the old model, so
    the paper is not told two models produced it."""
    first = _started(tmp_path)
    _write_config(first.quest_root, "claude-opus-5")
    eng = Engine(_cfg(tmp_path, "claude-opus-5"), resume_quest_id=first.quest_id)
    _skip_setup(eng)

    async def connected() -> None:
        raise _Stop

    eng._connect_llm = connected  # type: ignore[method-assign]
    with pytest.raises(_Stop):
        await eng.run()
    assert "nothing had run on gpt-5.6-luna yet" in capsys.readouterr().out
    events = audit_log.read(eng.audit.path)
    assert [e for e in events if e.get("kind") == "model_changed"][0]["before_any_step"] is True
    assert plan_settings.model_disclosure(events) == ""


@pytest.mark.asyncio
async def test_putting_an_edit_back_after_a_default_moved_does_not_stop(tmp_path: Path) -> None:
    """A stop for a real edit, while check() also recorded an FI default that moved: the record's new hash goes into
    the trace, so putting the edit back resumes (it used to stop with "the record ... was changed after it was
    approved")."""
    first = _started(tmp_path)
    _made_calls(first)
    data = json.loads((first.fi_dir / plan_settings.NAME).read_text(encoding="utf-8"))
    data["settings"]["engine.execute_replicates"] = 99  # an older FI's default for a key the file never set
    (first.fi_dir / plan_settings.NAME).write_text(json.dumps(data), encoding="utf-8")
    first.audit.append("plan_settings_recorded", sha256=__import__("hashlib").sha256(
        (first.fi_dir / plan_settings.NAME).read_bytes()).hexdigest())
    with (first.quest_root / "config.yaml").open("a", encoding="utf-8") as f:
        f.write("engine:\n  oracle_check: warn\n")

    async def no_llm() -> None:
        raise AssertionError("nothing may run")

    edited = Engine(_cfg(tmp_path, oracle_check="warn"), resume_quest_id=first.quest_id)
    edited._connect_llm = no_llm  # type: ignore[method-assign]
    await edited.run()
    assert "engine.oracle_check" in (edited.quest_root / "NEXT_STEP.md").read_text(encoding="utf-8")
    (edited.quest_root / "NEXT_STEP.md").unlink()
    _write_config(first.quest_root, "gpt-5.6-luna")

    back = Engine(_cfg(tmp_path), resume_quest_id=first.quest_id)
    _skip_setup(back)

    async def connected() -> None:
        raise _Stop

    back._connect_llm = connected  # type: ignore[method-assign]
    with pytest.raises(_Stop):
        await back.run()
    assert not (back.quest_root / "NEXT_STEP.md").exists()


def test_update_asks_unless_the_chat_says_it_was_approved(monkeypatch: pytest.MonkeyPatch) -> None:
    """--update with no terminal must not approve anything on its own (a pipe, a script, an agent's shell): only the
    VS Code chat, after the person chose "approve as it is", skips the questions."""
    import launch

    seen: dict[str, Any] = {}

    async def fake_flow(**kw: Any) -> int:
        seen.update(kw)
        return 0

    monkeypatch.setattr("core.interview_update.run_update_flow", fake_flow)
    monkeypatch.delenv("FI_UPDATE_APPROVE_AS_IS", raising=False)
    kw = dict(quest_id="q", output_root=Path("."), vscode_bridge_port=0, interactive=False, supervisor=None)
    asyncio.run(launch._run_update(**kw))
    assert seen["ask"] is True
    monkeypatch.setenv("FI_UPDATE_APPROVE_AS_IS", "1")
    asyncio.run(launch._run_update(**kw))
    assert seen["ask"] is False


def test_the_paper_is_told_nothing_when_the_model_never_changed() -> None:
    assert plan_settings.model_disclosure([{"kind": "quest_started"}]) == ""


def test_single_steps_still_on_the_old_model_are_named(tmp_path: Path) -> None:
    fi = tmp_path / ".fi"
    plan_settings.record(fi, _cfg(tmp_path, "gpt-5.6-luna", node_models={"cross_check": "gpt-5.6-luna"}))
    now = _cfg(tmp_path, "claude-opus-5", node_models={"cross_check": "gpt-5.6-luna"})
    lines = plan_settings.model_change_lines(plan_settings.model_changes(fi, now), now.provider.node_models)
    assert lines[0].startswith("the model changes from gpt-5.6-luna to claude-opus-5")
    assert any(ln.startswith("cross_check stay on gpt-5.6-luna") for ln in lines), lines


def test_update_leaves_the_model_change_for_the_quest_to_record(tmp_path: Path) -> None:
    """--update approves the other settings; the model change is left for the quest's start to take and record, so
    the trace and the paper still learn that the model changed."""
    from core.interview_update import approve_settings

    root = tmp_path / "q"
    _write_config(root, "gpt-5.6-luna")
    plan_settings.record(root / ".fi", _cfg(tmp_path, "gpt-5.6-luna"), root)
    said: list[str] = []
    approved = approve_settings(root, _cfg(tmp_path, "claude-opus-5", oracle_check="warn"), say=said.append)
    assert approved and all("provider.model" not in ln for ln in approved)
    assert any("the model changes from gpt-5.6-luna to claude-opus-5" in ln for ln in said)
    assert plan_settings.model_changes(root / ".fi", _cfg(tmp_path, "claude-opus-5"))


def test_update_from_the_chat_asks_nothing_and_resumes(tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
                                                        capsys: pytest.CaptureFixture[str]) -> None:
    """The VS Code chat's /update runs --update in the chat after the person chose to approve config.yaml as it is
    (``ask=False``): nothing is asked, those settings are approved, and the quest resumes."""
    from core.interview import InterviewAnswers, answers_to_yaml
    from core.interview_update import run_update_flow

    output_root = tmp_path / "outputs"
    root = output_root / "q-chat"
    root.mkdir(parents=True)
    yaml_text = answers_to_yaml(InterviewAnswers(
        topic="energy drift", title="Energy drift", output_kinds=["paper_md"], paper_format="generic",
        no_simulation=False, provider="vscode_extension", provider_model="gpt-5.6-luna", knowledge_enabled=False,
        study_depth="journal-length", comparative_baseline="", success_metric="", budget="",
        clarify_mode="auto", review_panel=[],
    ), frontend="cli")
    (root / "config.yaml").write_text(yaml_text, encoding="utf-8")
    plan_settings.record(root / ".fi", Config.from_yaml(root / "config.yaml"), root)
    (root / "config.yaml").write_text(yaml_text.replace('"gpt-5.6-luna"', '"claude-opus-5"'), encoding="utf-8")

    def no_prompt(*_a: Any) -> Any:
        raise AssertionError("no question may be asked without a terminal")

    monkeypatch.setattr("launch._cli_prompt_for", no_prompt)
    seen: dict[str, Any] = {}

    async def fake_run_one(cfg: Config, **kw: Any) -> int:
        seen["model"] = cfg.provider.model
        seen["port"] = cfg.provider.extra.get("bridge_port")
        seen.update(kw)
        return 0

    from launch import _apply_vscode_bridge_override

    before = (root / "config.yaml").read_text(encoding="utf-8")
    rc = asyncio.run(run_update_flow(
        quest_id="q-chat", output_root=output_root, vscode_bridge_port=4321, interactive=False, supervisor=None,
        run_one=fake_run_one, apply_vscode_bridge_override=_apply_vscode_bridge_override, ask=False,
    ))
    assert rc == 0
    assert seen["model"] == "claude-opus-5" and seen["port"] == 4321 and seen["resume_quest_id"] == "q-chat"
    assert (root / "config.yaml").read_text(encoding="utf-8") == before, "nothing asked, so nothing rewritten"
    out = capsys.readouterr().out
    assert "[FI] update: " in out and "the model changes from gpt-5.6-luna to claude-opus-5" in out


def test_resuming_with_another_config_brings_the_quest_copy_up_to_date(tmp_path: Path) -> None:
    """`--config edited.yaml --resume <id>` runs edited.yaml; the quest's own config.yaml must follow it, or the next
    `/resume` (which reads the quest's copy) quietly goes back to the old model."""
    from launch import _refresh_quest_config

    dest = tmp_path / "q" / "config.yaml"
    _write_config(dest.parent, "gpt-5.6-luna")
    source = tmp_path / "edited.yaml"
    source.write_text(HEADER + "topic: x\nprovider:\n  name: openai\n  model: claude-opus-5\n", encoding="utf-8")
    old = dest.read_text(encoding="utf-8")
    kept = _refresh_quest_config(source, dest)
    assert kept is not None and kept.name.startswith("config.yaml.before-resume-")
    assert "claude-opus-5" in dest.read_text(encoding="utf-8")
    assert kept.read_text(encoding="utf-8") == old
    assert _refresh_quest_config(source, dest) is None, "already the same"
    assert _refresh_quest_config(dest, dest) is None, "the quest's own copy"
    # A second, different resume keeps the first backup too.
    source.write_text(HEADER + "topic: x\nprovider:\n  name: openai\n  model: m3\n", encoding="utf-8")
    second = _refresh_quest_config(source, dest)
    assert second is not None and second != kept and kept.read_text(encoding="utf-8") == old


@pytest.mark.asyncio
async def test_after_a_resume_with_a_new_model_cost_jsonl_names_it(tmp_path: Path) -> None:
    """The model the resumed quest's calls go to, end to end through the VS Code bridge transport: the hint the
    extension receives and the model cost.jsonl records are the new one."""
    hints: list[str] = []

    async def served(reader: asyncio.StreamReader, writer: asyncio.StreamWriter) -> None:
        while line := await reader.readline():
            msg = json.loads(line)
            if msg.get("type") != "lm_request":
                continue
            hints.append(msg.get("model_hint") or "")
            writer.write((json.dumps({
                "type": "lm_done", "id": msg["id"], "content": "ok",
                "served_model": {"id": msg.get("model_hint") or "panel-model", "vendor": "copilot"},
            }) + "\n").encode("utf-8"))
            await writer.drain()

    server = await asyncio.start_server(served, "127.0.0.1", 0)
    port = server.sockets[0].getsockname()[1]
    try:
        bridge = {"bridge_port": port}
        first = _started(tmp_path, "gpt-5.6-luna", name="vscode_extension", extra=bridge)
        # Calls made before the change: cost.jsonl keeps them (it is append-only).
        (first.fi_dir / "cost.jsonl").write_text(json.dumps({"node": "ideate", "model": "gpt-5.6-luna"}) + "\n",
                                                  encoding="utf-8")
        _write_config(first.quest_root, "claude-opus-5")
        eng = Engine(_cfg(tmp_path, "claude-opus-5", name="vscode_extension", extra=bridge),
                     resume_quest_id=first.quest_id)
        _skip_setup(eng)
        real_connect = eng._connect_llm

        async def connect_and_call() -> None:
            await real_connect()
            await eng._chat("hello", node="ideate")
            raise _Stop

        eng._connect_llm = connect_and_call  # type: ignore[method-assign]
        with pytest.raises(_Stop):
            await eng.run()
        if eng._client is not None:
            await eng._client.aclose()
    finally:
        server.close()
        await server.wait_closed()
    assert hints == ["claude-opus-5"]
    rows = [json.loads(ln) for ln in (eng.fi_dir / "cost.jsonl").read_text(encoding="utf-8").splitlines() if ln.strip()]
    assert rows[-1]["model"] == "claude-opus-5", rows


def test_config_changed_to_b_but_the_chat_panel_runs_c_the_paper_names_c_not_b(
        tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    """Earlier steps ran on A; config.yaml now names B; this run is resumed from the chat with C picked (launch.py puts C
    in provider.model and B in the chat panel's record). B never runs: the paper must name A and C, never B."""
    first = _started(tmp_path, "A")
    _made_calls(first, "A")
    _write_config(first.quest_root, "B")
    cfg = _cfg(tmp_path, "C", extra={Engine.CHAT_MODEL_KEY: {"before": "B", "after": "C"}})
    eng = Engine(cfg, resume_quest_id=first.quest_id)
    eng._take_model_change()
    eng._say_model_change()
    events = audit_log.read(eng.audit.path)
    disclosed = plan_settings.model_disclosure(events)
    assert "A for the steps before the change, C after it" in disclosed
    assert "B after it" not in disclosed
    changes = [e for e in events if e["kind"] == "model_changed"]
    assert len(changes) == 2 and changes[0]["run_uses"] == "C"
    out = capsys.readouterr().out
    assert "config.yaml's model changes from A to B; this run uses the chat panel's model C" in out
    assert "from A to B from here on" not in out, "one sentence, not 'from here on B' then 'not B'"


def test_resumed_again_on_the_chat_panel_s_model_with_no_named_calls_is_no_new_change(tmp_path: Path) -> None:
    """A quest started from the chat on C (config A) whose calls named no model (the picker on Auto), resumed from
    the chat on C again: nothing changed, so the paper is not told A made part of it."""
    first = _started(tmp_path, "A")
    _made_calls(first, "unnamed")
    first._audit("model_changed", before="A", after="C", source="the model picked in the VS Code chat panel",
                 before_any_step=True)
    cfg = _cfg(tmp_path, "C", extra={Engine.CHAT_MODEL_KEY: {"before": "A", "after": "C"}})
    eng = Engine(cfg, resume_quest_id=first.quest_id)
    eng._take_model_change()
    eng._say_model_change()
    events = audit_log.read(eng.audit.path)
    assert len([e for e in events if e["kind"] == "model_changed"]) == 1
    assert plan_settings.model_disclosure(events) == ""


def test_a_change_only_to_the_model_that_already_ran_is_not_disclosed(tmp_path: Path) -> None:
    """Config's A -> B, but the chat panel runs C, which is what the earlier steps ran on too: one model made it."""
    ev = [{"kind": "model_changed", "changes": [{"setting": "provider.model", "label": "the model", "from": "A",
                                                   "to": "B"}], "run_uses": "C", "before_any_step": False}]
    assert plan_settings.model_disclosure(ev) == ""
