/**
 * interview-core — pure-logic half of the interview module, free of
 * any `vscode` imports so it can be unit-tested from plain Node.
 *
 * The UI half (`interview.ts`) lives next to this file; it owns the
 * `showInputBox` / `showQuickPick` flow. Anything that doesn't touch
 * `vscode.*` goes here so the tests can exercise it without the
 * VSCode runtime.
 */
import * as fs from "fs";
import * as path from "path";

export interface InterviewAnswers {
    topic: string;
    title: string;
    output_kinds: string[];
    clarify_mode: "off" | "auto" | "interactive";
    review_panel: string[];           // empty = single reviewer
    knowledge_enabled: boolean;
    max_iterations: number;
}

/**
 * Render the interview answers as a complete config.yaml string,
 * ready to write to disk. The provider block is always
 * `vscode_extension` — we're generating this from inside the FI
 * VSCode extension, so the bridge transport is the only sensible
 * default. A user who wants a different provider can edit the YAML
 * afterwards and re-run via `@fi /start <path>`.
 */
export function answersToYaml(answers: InterviewAnswers): string {
    const indent = "  ";
    const lines: string[] = [];

    lines.push("# Auto-generated by the Frontier Insight VSCode extension.");
    lines.push("# You can edit this file and re-run with `@fi /start <path>`.");
    lines.push("");

    lines.push("topic: |");
    for (const line of answers.topic.split("\n")) {
        lines.push(`${indent}${line}`);
    }
    lines.push("");

    // Always quote string-valued scalars. YAML 1.1's "Norway
    // problem" auto-coerces unquoted bareword tokens like
    // `off` / `on` / `no` / `yes` / `n` / `y` / `false` / `true`
    // into Python booleans before the schema validator sees them.
    // `clarify_mode: off` was the most common bite; quoting every
    // string field is the cheap, defensive fix.
    lines.push(`title: "${yamlEscape(answers.title)}"`);
    lines.push("");

    lines.push("provider:");
    lines.push(`${indent}name: "vscode_extension"`);
    lines.push("");

    lines.push("engine:");
    lines.push(`${indent}framework: "langgraph"`);
    lines.push(`${indent}max_iterations: ${answers.max_iterations}`);
    lines.push(`${indent}review_loop: true`);
    lines.push(`${indent}clarify_mode: "${answers.clarify_mode}"`);
    // ---- COST DISCIPLINE — these defaults are LOW so a basic quest is
    // ~6 LLM calls instead of ~26. Each line below switches off an
    // expensive feature that the Python defaults turn ON. A user who
    // wants the full research-quality loop edits the YAML by hand.
    //
    //   ideate_reflect: false  → -1 LLM call per quest (no chosen-idea critique pass)
    //   cross_check_per_finding_k: 0  → -2 calls × N findings × iterations
    //                                   (was the single biggest Copilot-budget burner)
    //   enable_analyze_reroute: false → keeps the quest to ONE design iteration;
    //                                   no re_experiment / broaden_lit loops.
    //
    // The user can still hit the heavy path by editing the YAML.
    lines.push(`${indent}ideate_reflect: false`);
    lines.push(`${indent}cross_check_per_finding_k: 0`);
    lines.push(`${indent}enable_analyze_reroute: false`);
    if (answers.review_panel.length > 0) {
        lines.push(`${indent}review_panel:`);
        for (const persona of answers.review_panel) {
            lines.push(`${indent}${indent}- "${yamlEscape(persona)}"`);
        }
    } else {
        lines.push(`${indent}review_panel: []`);
    }
    lines.push("");

    lines.push("execution:");
    lines.push(`${indent}sandbox: "venv"`);
    lines.push(`${indent}timeout_s: 600`);
    lines.push("");

    lines.push("knowledge:");
    lines.push(`${indent}enabled: ${answers.knowledge_enabled ? "true" : "false"}`);
    if (!answers.knowledge_enabled) {
        lines.push(`${indent}external_fallback: ["openalex", "arxiv", "crossref"]`);
        // `source_routing: manual` skips the LLM-driven catalog source
        // picker — saves 1 call per asearch (so ~3–5 calls per quest).
        // With Axon disabled the router would otherwise fire for every
        // ideate-seed and literature retrieval.
        lines.push(`${indent}source_routing: "manual"`);
    }
    lines.push("");

    lines.push("output:");
    const quotedKinds = answers.output_kinds.map((k) => `"${yamlEscape(k)}"`).join(", ");
    lines.push(`${indent}kinds: [${quotedKinds}]`);
    lines.push(`${indent}paper_format: "generic"`);
    lines.push(`${indent}output_dir: "./outputs"`);
    lines.push("");

    return lines.join("\n");
}

/**
 * Write the generated YAML to a draft folder inside the repo's
 * `outputs/_drafts/` so it lives adjacent to where the quest's
 * artifacts will land. Returns the absolute path to the file.
 */
export function writeInterviewYaml(
    answers: InterviewAnswers,
    repoPath: string,
): string {
    const yaml = answersToYaml(answers);
    const draftDir = path.join(repoPath, "outputs", "_drafts");
    fs.mkdirSync(draftDir, { recursive: true });
    const filename = `${stamp()}-${slugifyTitle(answers.title)}.yaml`;
    const filepath = path.join(draftDir, filename);
    fs.writeFileSync(filepath, yaml, "utf-8");
    return filepath;
}

/**
 * Escape a string for inclusion in a YAML double-quoted scalar.
 * Handles the two characters that matter inside `"..."`: backslash
 * and the closing double-quote. (Tabs/newlines aren't possible here
 * because our inputs come from `showInputBox`, which is one-line.)
 */
export function yamlEscape(s: string): string {
    return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}


export function slugify(s: string): string {
    return s
        .toLowerCase()
        .replace(/[^a-z0-9\s-]/g, "")
        .replace(/\s+/g, "-")
        .replace(/-+/g, "-")
        .replace(/^-|-$/g, "");
}

function slugifyTitle(s: string): string {
    return s.replace(/[^a-z0-9-]/gi, "-").toLowerCase();
}

function stamp(): string {
    const d = new Date();
    const pad = (n: number) => String(n).padStart(2, "0");
    return (
        `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}` +
        `-${pad(d.getHours())}${pad(d.getMinutes())}`
    );
}

export function truncate(s: string, n: number): string {
    return s.length > n ? s.slice(0, n - 1) + "…" : s;
}
