"""The settings that decide how strictly a quest is checked, recorded when it first starts and compared on every
later start.

The interview's confirm screen shows these settings, and the person launches the quest on what it shows. A config
edited by hand afterwards (the quest's own ``config.yaml``, or a different ``--config`` passed to ``--resume``) could
otherwise turn a check down or drop a reviewer without anyone seeing it. So the first start of a quest the interview
wrote records the settings in ``.fi/approved_plan.json``; every later start compares, and a difference stops the quest
before anything runs, naming each setting as approved and as it is now. ``--update`` (the interview's own way to change
a quest) records the new settings, which is how a change is approved.

The model (``MODEL_SETTINGS``: the provider, the model and the per-step models) is recorded too, but a change to it
does not stop the quest: which model answers does not change what the result means or how strictly it is checked, and
changing it is an ordinary thing to do between two runs. It is taken as it is now, recorded here and in the quest's
trace, and said plainly (:func:`model_changes`, :func:`accept_models`, ``Engine.run``). The one model change that does
bear on the checks, a research quest's reviewers all ending up on one model, is stopped by
``Engine._review_models_stop`` before this record is read (also after the panel has reviewed once). The multi-model
ensemble is not a model setting here: it decides how many models vote on a check, so a change to it still stops.

Only interview-written configs are recorded (their header says so): a config written by hand was never shown on a
confirm screen, so there is nothing to hold it to.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

NAME = "approved_plan.json"
SCHEMA = "fi.approved-plan/v1"
#: The first line of every config the interview writes (core/interview.py answers_to_yaml and the VS Code emitter).
INTERVIEW_MARK = "# Auto-generated by"

# (config path, what it is in plain words). Order is the order a difference is listed in.
SETTINGS: tuple[tuple[str, str], ...] = (
    ("rigor_profile", "how strictly the quest is checked"),
    ("result_use", "what the result is for"),
    ("provider.name", "the model provider"),
    ("provider.model", "the model"),
    ("provider.node_models", "models chosen for single steps"),
    ("provider.node_ensemble", "the multi-model ensemble"),
    ("engine.review_panel", "the reviewers"),
    ("engine.protocol_check", "what a protocol problem does"),
    ("engine.oracle_check", "what a failed reference check does"),
    ("engine.numeric_warnings", "what a numeric warning does"),
    ("engine.run_manifest_check", "what a run-record problem does"),
    ("engine.cross_check_verify", "verifying the findings against the literature"),
    ("engine.cross_check_per_finding_k", "sources checked per finding"),
    ("engine.ideate_reflect", "self-critique of the ideas"),
    ("engine.enable_analyze_reroute", "redesign after the analysis"),
    ("engine.evidence_gate", "the evidence check before writing"),
    ("engine.phased", "exploring first, then confirming once on data or seeds never seen"),
    ("engine.max_iterations", "how many times the design may be revised"),
    ("engine.execute_replicates", "how many independent runs (seeds) the experiment makes"),
    ("engine.oracle_repair_attempts", "how many repairs a failed reference check allows"),
    ("engine.exec_reflect_max_iterations", "how many repairs a crashed script allows"),
    ("engine.claim_grounding", "checking the paper's claims against the sources"),
    ("engine.review_loop", "revising the paper after its review"),
    ("pauses.review", "stopping for you to review the result"),
    ("execution.sandbox", "where the experiment runs"),
    ("execution.shared_interpreter", "sharing FI's own Python with the experiment"),
    ("execution.system_site_packages", "letting the experiment see system packages"),
    ("execution.split_analysis", "keeping the simulation and its analysis in two scripts"),
    ("execution.split_failure", "what a missing second script does"),
    ("pauses.plan", "stopping to read the plan"),
)

#: The settings that name the model. Recorded like the others, but a change to one is taken as it is, recorded and
#: said, never a stop (see the module docstring). The ensemble (``provider.node_ensemble``) is not one of them: it
#: decides how many models vote on a check, so a change to it still needs approving.
MODEL_SETTINGS: frozenset[str] = frozenset({
    "provider.name", "provider.model", "provider.node_models",
})


def _value(cfg: Any, path: str) -> Any:
    obj = cfg
    for part in path.split("."):
        obj = getattr(obj, part, None)
    if hasattr(obj, "model_dump"):
        obj = obj.model_dump(mode="json")
    elif isinstance(obj, dict):
        obj = {k: (v.model_dump(mode="json") if hasattr(v, "model_dump") else v) for k, v in obj.items()}
    # A round trip through JSON, so a value read back from the record compares equal to the live one.
    return json.loads(json.dumps(obj, default=str))


def settings_of(cfg: Any) -> dict[str, Any]:
    """The recorded settings of a loaded Config (after the rigor profile has filled in what it sets). The model picked
    in the VS Code chat panel for one run (``provider.extra['chat_panel_model']``, set by ``launch.py
    --vscode-chat-model``) is that run's choice, said in run.log and recorded in the trace, not a change to the
    config's settings: the config's own model is what is compared."""
    settings = {path: _value(cfg, path) for path, _label in SETTINGS}
    extra = getattr(getattr(cfg, "provider", None), "extra", None)
    change = extra.get("chat_panel_model") if isinstance(extra, dict) else None
    if isinstance(change, dict) and "before" in change:
        settings["provider.model"] = change.get("before") or None
    return settings


def _show(value: Any) -> str:
    if value is None or value == [] or value == {}:
        return "(none)"
    if isinstance(value, bool):
        return "on" if value else "off"
    if isinstance(value, list):
        return ", ".join(str(v) for v in value)
    if isinstance(value, dict):
        return json.dumps(value, sort_keys=True)
    return str(value)


def differences(approved: dict[str, Any], now: dict[str, Any], *, models: bool = True) -> list[str]:
    """One plain line per setting that changed: what it is, as approved, and as it is now. ``models=False`` leaves
    out the model settings (:data:`MODEL_SETTINGS`), which never need an approval."""
    out = []
    for path, label in SETTINGS:
        if not models and path in MODEL_SETTINGS:
            continue
        if path in approved and approved.get(path) != now.get(path):
            out.append(f"{label} (`{path}`): approved {_show(approved.get(path))}, now {_show(now.get(path))}")
    return out


def _raw(quest_root: Path) -> dict[str, Any] | None:
    """The quest's config.yaml as a mapping, or None when it cannot be read."""
    try:
        import yaml

        data = yaml.safe_load((quest_root / "config.yaml").read_text(encoding="utf-8"))
    except (OSError, ValueError, ImportError):
        return None
    return data if isinstance(data, dict) else None


def _set_in(raw: Any, path: str) -> bool:
    """Whether the config file itself sets ``path`` (a dotted key)."""
    node = raw
    for part in path.split("."):
        if not isinstance(node, dict) or part not in node:
            return False
        node = node[part]
    return True


def _write(fi_dir: Path, settings: dict[str, Any], explicit: list[str]) -> None:
    fi_dir.mkdir(parents=True, exist_ok=True)
    (fi_dir / NAME).write_text(
        json.dumps({"schema": SCHEMA, "settings": settings, "explicit": sorted(explicit)}, indent=2, sort_keys=True)
        + chr(10),
        encoding="utf-8",
    )


def record(fi_dir: Path, cfg: Any, quest_root: Path | None = None, *,
           models_from: dict[str, Any] | None = None) -> None:
    """Record ``cfg``'s settings as the approved ones (the first start, or ``--update``), with which of them the
    config file set itself (``explicit``): only those can be edited by hand. ``models_from`` (the record as it was)
    keeps the model settings as they were recorded, so the quest's next start still finds the model change and says
    it (``--update`` approves the other settings; a model needs no approval)."""
    raw = _raw(quest_root) if quest_root is not None else None
    explicit = [p for p, _label in SETTINGS if raw is None or _set_in(raw, p)]
    settings = settings_of(cfg)
    if models_from:
        settings.update({p: models_from[p] for p in MODEL_SETTINGS if p in models_from})
    _write(fi_dir, settings, explicit)


def check(quest_root: Path, fi_dir: Path, cfg: Any) -> list[str]:
    """Compare ``cfg`` with the recorded settings and return the differences (empty: go on).

    With nothing recorded yet: an interview-written config (``quest_root/config.yaml`` starts with the interview's
    header) is recorded now, as it was approved on the confirm screen; any other config is left unrecorded. A record
    that is there but cannot be read (not JSON, another schema, its fields missing) is a difference of its own, never
    written again: rewriting it would approve whatever the config says now, weaker or not. Only ``--update``, which
    shows the settings to the person, records them again.

    A setting the config file neither set when it was approved nor sets now took FI's default, and a newer FI may
    have changed that default: not an edit anyone made, so it is recorded as it is now instead of stopping the quest.
    Removing a line counts as an edit (it was set, and is not now).

    A change to a model setting (:data:`MODEL_SETTINGS`) is never returned: :func:`model_changes` names it and
    :func:`accept_models` records it."""
    path = fi_dir / NAME
    present = path.is_file()
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        approved = data["settings"] if data.get("schema") == SCHEMA else None
        # An empty list is a record that the file set none of them; only a record from before the list is "all".
        explicit = set(data["explicit"]) if isinstance(data.get("explicit"), list) else {p for p, _label in SETTINGS}
    except (OSError, ValueError, KeyError, TypeError, AttributeError):
        approved, explicit = None, set()
    if present and not isinstance(approved, dict):
        return [f"the record of the settings this quest was approved with ({path}) cannot be read, so a change since "
                f"then cannot be told from none; approve the settings again with --update"]
    if not isinstance(approved, dict):
        try:
            written_by_interview = (quest_root / "config.yaml").read_text(encoding="utf-8").startswith(INTERVIEW_MARK)
        except OSError:
            written_by_interview = False
        if written_by_interview:
            record(fi_dir, cfg, quest_root)
        return []
    now = settings_of(cfg)
    missing = [p for p, _label in SETTINGS if p not in approved]
    if missing:
        # A setting added to this list after the quest was approved (a newer FI): recorded as it is now, so a hand
        # edit of it from here on stops the quest like any other. Whether the file sets it counts as it does now.
        # Written only on a start that goes on (the engine then records the record's new hash); a start that stops
        # for another change leaves the record as it was.
        raw_now = _raw(quest_root)
        approved = {**approved, **{p: now.get(p) for p in missing}}
        explicit = explicit | {p for p in missing if raw_now is None or _set_in(raw_now, p)}
    changed = [p for p, _label in SETTINGS
               if p not in MODEL_SETTINGS and p in approved and approved.get(p) != now.get(p)]
    if not changed:
        if missing:
            _write(fi_dir, approved, sorted(explicit))
        return []
    raw = _raw(quest_root)
    if raw is not None:
        drifted = [p for p in changed if p not in explicit and not _set_in(raw, p)]
        if drifted:
            approved = {**approved, **{p: now.get(p) for p in drifted}}
            if not differences(approved, now, models=False):
                # Written only when the start goes on (the engine records the new hash); a start that stops for a
                # hand edit leaves the record as it was, so putting the edit back is not read as an edited record.
                _write(fi_dir, approved, sorted(explicit))
    return differences(approved, now, models=False)


def _read(fi_dir: Path) -> tuple[dict[str, Any] | None, set[str]]:
    """The recorded settings and which of them the config file set, or ``(None, set())`` when there is no readable
    record."""
    try:
        data = json.loads((fi_dir / NAME).read_text(encoding="utf-8"))
        approved = data["settings"] if data.get("schema") == SCHEMA else None
        explicit = set(data["explicit"]) if isinstance(data.get("explicit"), list) else {p for p, _label in SETTINGS}
    except (OSError, ValueError, KeyError, TypeError, AttributeError):
        return None, set()
    return (approved, explicit) if isinstance(approved, dict) else (None, set())


def model_changes(fi_dir: Path, cfg: Any) -> list[dict[str, Any]]:
    """Each model setting (:data:`MODEL_SETTINGS`) whose value differs from the recorded one: ``{"setting", "label",
    "from", "to"}``. Empty when nothing is recorded (there is nothing to compare with) or nothing changed."""
    approved, _explicit = _read(fi_dir)
    if approved is None:
        return []
    now = settings_of(cfg)
    return [{"setting": p, "label": label, "from": approved.get(p), "to": now.get(p)}
            for p, label in SETTINGS
            if p in MODEL_SETTINGS and p in approved and approved.get(p) != now.get(p)]


def accept_models(fi_dir: Path, cfg: Any, quest_root: Path | None = None) -> None:
    """Record the model settings as they are now, leaving every other recorded setting as it was approved."""
    approved, explicit = _read(fi_dir)
    if approved is None:
        return
    now = settings_of(cfg)
    raw = _raw(quest_root) if quest_root is not None else None
    for p in MODEL_SETTINGS:
        approved[p] = now.get(p)
        if raw is not None:
            (explicit.add if _set_in(raw, p) else explicit.discard)(p)
    _write(fi_dir, approved, sorted(explicit))


def model_disclosure(events: list[dict[str, Any]]) -> str:
    """What the paper must say when more than one model produced the quest (a ``model_changed`` event in its trace),
    or an empty string when the model never changed."""
    changes = [e for e in events if e.get("kind") == "model_changed" and not e.get("before_any_step")]
    bullets: list[str] = []
    for e in changes:
        for c in e.get("changes") or []:
            # config.yaml's new model did not run: the chat panel's model did, and has its own event.
            if isinstance(c, dict) and not (e.get("run_uses") and c.get("setting") == "provider.model"):
                bullets.append(f"- {c.get('label') or c.get('setting')}: {_show(c.get('from'))} for the steps before "
                               f"the change, {_show(c.get('to'))} after it")
        if not e.get("changes") and e.get("after"):
            # The chat panel's model, or the model that answered the calls, as the engine recorded it.
            bullets.append(f"- the model: {_show(e.get('before'))} for the steps before the change, "
                           f"{_show(e.get('after'))} after it")
    if not bullets:
        return ""
    lines = ["More than one model produced this study: its model was changed while the quest was under way. State "
             "this in the methods, in these terms (which model made each step is in the quest's record of its model "
             "calls):"]
    return "\n".join(lines + list(dict.fromkeys(bullets)))


def model_change_lines(changes: list[dict[str, Any]], node_models: dict[str, Any] | None = None, *,
                       made: bool = True) -> list[str]:
    """The plain sentences a model change is announced with: the main model's own sentence first ("the model changes
    from A to B from here on; steps already done were made by A", or, when ``made`` is False, that nothing had run on
    A yet), then any other model setting that changed, then the single steps that ``provider.node_models`` still keeps
    on the old model."""
    lines: list[str] = []
    old_main = None
    for c in changes:
        if c["setting"] == "provider.model":
            old_main = c["from"]
            done = (f"steps already done were made by {_show(c['from'])}" if made
                    else f"nothing had run on {_show(c['from'])} yet")
            lines.append(f"the model changes from {_show(c['from'])} to {_show(c['to'])} from here on; {done}")
    for c in changes:
        if c["setting"] != "provider.model":
            lines.append(f"{c['label']} (`{c['setting']}`): {_show(c['from'])} until now, {_show(c['to'])} from here on")
    if old_main and isinstance(node_models, dict):
        kept = sorted(str(node) for node, model in node_models.items() if model == old_main)
        if kept:
            lines.append(f"{', '.join(kept)} stay on {old_main}: `provider.node_models` in config.yaml names it for "
                         "them; change it there too to move them")
    return lines
