"""The settings that decide how strictly a quest is checked, recorded when it first starts and compared on every
later start.

The interview's confirm screen shows these settings, and the person launches the quest on what it shows. A config
edited by hand afterwards (the quest's own ``config.yaml``, or a different ``--config`` passed to ``--resume``) could
otherwise turn a check down, drop a reviewer or switch the model without anyone seeing it. So the first start of a
quest the interview wrote records the settings in ``.fi/approved_plan.json``; every later start compares, and a
difference stops the quest before anything runs, naming each setting as approved and as it is now. ``--update`` (the
interview's own way to change a quest) records the new settings, which is how a change is approved.

Only interview-written configs are recorded (their header says so): a config written by hand was never shown on a
confirm screen, so there is nothing to hold it to.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

NAME = "approved_plan.json"
SCHEMA = "fi.approved-plan/v1"
#: The first line of every config the interview writes (core/interview.py answers_to_yaml and the VS Code emitter).
INTERVIEW_MARK = "# Auto-generated by"

# (config path, what it is in plain words). Order is the order a difference is listed in.
SETTINGS: tuple[tuple[str, str], ...] = (
    ("rigor_profile", "how strictly the quest is checked"),
    ("result_use", "what the result is for"),
    ("provider.name", "the model provider"),
    ("provider.model", "the model"),
    ("provider.node_models", "models chosen for single steps"),
    ("provider.node_ensemble", "the multi-model ensemble"),
    ("engine.review_panel", "the reviewers"),
    ("engine.protocol_check", "what a protocol problem does"),
    ("engine.oracle_check", "what a failed reference check does"),
    ("engine.numeric_warnings", "what a numeric warning does"),
    ("engine.run_manifest_check", "what a run-record problem does"),
    ("engine.cross_check_verify", "verifying the findings against the literature"),
    ("engine.cross_check_per_finding_k", "sources checked per finding"),
    ("engine.ideate_reflect", "self-critique of the ideas"),
    ("engine.enable_analyze_reroute", "redesign after the analysis"),
    ("engine.evidence_gate", "the evidence check before writing"),
    ("engine.max_iterations", "how many times the design may be revised"),
    ("engine.execute_replicates", "how many independent runs (seeds) the experiment makes"),
    ("engine.oracle_repair_attempts", "how many repairs a failed reference check allows"),
    ("engine.exec_reflect_max_iterations", "how many repairs a crashed script allows"),
    ("engine.claim_grounding", "checking the paper's claims against the sources"),
    ("engine.review_loop", "revising the paper after its review"),
    ("pauses.review", "stopping for you to review the result"),
    ("execution.sandbox", "where the experiment runs"),
    ("execution.shared_interpreter", "sharing FI's own Python with the experiment"),
    ("execution.system_site_packages", "letting the experiment see system packages"),
    ("execution.split_analysis", "keeping the simulation and its analysis in two scripts"),
    ("execution.split_failure", "what a missing second script does"),
    ("pauses.plan", "stopping to read the plan"),
)


def _value(cfg: Any, path: str) -> Any:
    obj = cfg
    for part in path.split("."):
        obj = getattr(obj, part, None)
    if hasattr(obj, "model_dump"):
        obj = obj.model_dump(mode="json")
    elif isinstance(obj, dict):
        obj = {k: (v.model_dump(mode="json") if hasattr(v, "model_dump") else v) for k, v in obj.items()}
    # A round trip through JSON, so a value read back from the record compares equal to the live one.
    return json.loads(json.dumps(obj, default=str))


def settings_of(cfg: Any) -> dict[str, Any]:
    """The recorded settings of a loaded Config (after the rigor profile has filled in what it sets)."""
    return {path: _value(cfg, path) for path, _label in SETTINGS}


def _show(value: Any) -> str:
    if value is None or value == [] or value == {}:
        return "(none)"
    if isinstance(value, bool):
        return "on" if value else "off"
    if isinstance(value, list):
        return ", ".join(str(v) for v in value)
    if isinstance(value, dict):
        return json.dumps(value, sort_keys=True)
    return str(value)


def differences(approved: dict[str, Any], now: dict[str, Any]) -> list[str]:
    """One plain line per setting that changed: what it is, as approved, and as it is now."""
    out = []
    for path, label in SETTINGS:
        if path in approved and approved.get(path) != now.get(path):
            out.append(f"{label} (`{path}`): approved {_show(approved.get(path))}, now {_show(now.get(path))}")
    return out


def _raw(quest_root: Path) -> dict[str, Any] | None:
    """The quest's config.yaml as a mapping, or None when it cannot be read."""
    try:
        import yaml

        data = yaml.safe_load((quest_root / "config.yaml").read_text(encoding="utf-8"))
    except (OSError, ValueError, ImportError):
        return None
    return data if isinstance(data, dict) else None


def _set_in(raw: Any, path: str) -> bool:
    """Whether the config file itself sets ``path`` (a dotted key)."""
    node = raw
    for part in path.split("."):
        if not isinstance(node, dict) or part not in node:
            return False
        node = node[part]
    return True


def _write(fi_dir: Path, settings: dict[str, Any], explicit: list[str]) -> None:
    fi_dir.mkdir(parents=True, exist_ok=True)
    (fi_dir / NAME).write_text(
        json.dumps({"schema": SCHEMA, "settings": settings, "explicit": sorted(explicit)}, indent=2, sort_keys=True)
        + chr(10),
        encoding="utf-8",
    )


def record(fi_dir: Path, cfg: Any, quest_root: Path | None = None) -> None:
    """Record ``cfg``'s settings as the approved ones (the first start, or ``--update``), with which of them the
    config file set itself (``explicit``): only those can be edited by hand."""
    raw = _raw(quest_root) if quest_root is not None else None
    explicit = [p for p, _label in SETTINGS if raw is None or _set_in(raw, p)]
    _write(fi_dir, settings_of(cfg), explicit)


def check(quest_root: Path, fi_dir: Path, cfg: Any) -> list[str]:
    """Compare ``cfg`` with the recorded settings and return the differences (empty: go on).

    With nothing recorded yet: an interview-written config (``quest_root/config.yaml`` starts with the interview's
    header) is recorded now, as it was approved on the confirm screen; any other config is left unrecorded. A record
    that is there but cannot be read (not JSON, another schema, its fields missing) is a difference of its own, never
    written again: rewriting it would approve whatever the config says now, weaker or not. Only ``--update``, which
    shows the settings to the person, records them again.

    A setting the config file neither set when it was approved nor sets now took FI's default, and a newer FI may
    have changed that default: not an edit anyone made, so it is recorded as it is now instead of stopping the quest.
    Removing a line counts as an edit (it was set, and is not now)."""
    path = fi_dir / NAME
    present = path.is_file()
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        approved = data["settings"] if data.get("schema") == SCHEMA else None
        # An empty list is a record that the file set none of them; only a record from before the list is "all".
        explicit = set(data["explicit"]) if isinstance(data.get("explicit"), list) else {p for p, _label in SETTINGS}
    except (OSError, ValueError, KeyError, TypeError, AttributeError):
        approved, explicit = None, set()
    if present and not isinstance(approved, dict):
        return [f"the record of the settings this quest was approved with ({path}) cannot be read, so a change since "
                f"then cannot be told from none; approve the settings again with --update"]
    if not isinstance(approved, dict):
        try:
            written_by_interview = (quest_root / "config.yaml").read_text(encoding="utf-8").startswith(INTERVIEW_MARK)
        except OSError:
            written_by_interview = False
        if written_by_interview:
            record(fi_dir, cfg, quest_root)
        return []
    now = settings_of(cfg)
    changed = [p for p, _label in SETTINGS if p in approved and approved.get(p) != now.get(p)]
    if not changed:
        return []
    raw = _raw(quest_root)
    if raw is not None:
        drifted = [p for p in changed if p not in explicit and not _set_in(raw, p)]
        if drifted:
            approved = {**approved, **{p: now.get(p) for p in drifted}}
            _write(fi_dir, approved, sorted(explicit))
    return differences(approved, now)
