"""The settings that decide how strictly a quest is checked, recorded when it first starts and compared on every
later start.

The interview's confirm screen shows these settings, and the person launches the quest on what it shows. A config
edited by hand afterwards (the quest's own ``config.yaml``, or a different ``--config`` passed to ``--resume``) could
otherwise turn a check down, drop a reviewer or switch the model without anyone seeing it. So the first start of a
quest the interview wrote records the settings in ``.fi/approved_plan.json``; every later start compares, and a
difference stops the quest before anything runs, naming each setting as approved and as it is now. ``--update`` (the
interview's own way to change a quest) records the new settings, which is how a change is approved.

Only interview-written configs are recorded (their header says so): a config written by hand was never shown on a
confirm screen, so there is nothing to hold it to.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

NAME = "approved_plan.json"
SCHEMA = "fi.approved-plan/v1"
#: The first line of every config the interview writes (core/interview.py answers_to_yaml and the VS Code emitter).
INTERVIEW_MARK = "# Auto-generated by"

# (config path, what it is in plain words). Order is the order a difference is listed in.
SETTINGS: tuple[tuple[str, str], ...] = (
    ("rigor_profile", "how strictly the quest is checked"),
    ("provider.name", "the model provider"),
    ("provider.model", "the model"),
    ("provider.node_models", "models chosen for single steps"),
    ("provider.node_ensemble", "the multi-model ensemble"),
    ("engine.review_panel", "the reviewers"),
    ("engine.protocol_check", "what a protocol problem does"),
    ("engine.oracle_check", "what a failed reference check does"),
    ("engine.numeric_warnings", "what a numeric warning does"),
    ("engine.run_manifest_check", "what a run-record problem does"),
    ("engine.cross_check_verify", "verifying the findings against the literature"),
    ("engine.cross_check_per_finding_k", "sources checked per finding"),
    ("engine.ideate_reflect", "self-critique of the ideas"),
    ("engine.enable_analyze_reroute", "redesign after the analysis"),
    ("engine.evidence_gate", "the evidence check before writing"),
    ("engine.max_iterations", "how many times the design may be revised"),
    ("execution.sandbox", "where the experiment runs"),
    ("execution.shared_interpreter", "sharing FI's own Python with the experiment"),
    ("execution.system_site_packages", "letting the experiment see system packages"),
    ("execution.split_analysis", "keeping the simulation and its analysis in two scripts"),
    ("execution.split_failure", "what a missing second script does"),
    ("pauses.plan", "stopping to read the plan"),
)


def _value(cfg: Any, path: str) -> Any:
    obj = cfg
    for part in path.split("."):
        obj = getattr(obj, part, None)
    if hasattr(obj, "model_dump"):
        obj = obj.model_dump(mode="json")
    elif isinstance(obj, dict):
        obj = {k: (v.model_dump(mode="json") if hasattr(v, "model_dump") else v) for k, v in obj.items()}
    # A round trip through JSON, so a value read back from the record compares equal to the live one.
    return json.loads(json.dumps(obj, default=str))


def settings_of(cfg: Any) -> dict[str, Any]:
    """The recorded settings of a loaded Config (after the rigor profile has filled in what it sets)."""
    return {path: _value(cfg, path) for path, _label in SETTINGS}


def _show(value: Any) -> str:
    if value is None or value == [] or value == {}:
        return "(none)"
    if isinstance(value, bool):
        return "on" if value else "off"
    if isinstance(value, list):
        return ", ".join(str(v) for v in value)
    if isinstance(value, dict):
        return json.dumps(value, sort_keys=True)
    return str(value)


def differences(approved: dict[str, Any], now: dict[str, Any]) -> list[str]:
    """One plain line per setting that changed: what it is, as approved, and as it is now."""
    out = []
    for path, label in SETTINGS:
        if path in approved and approved.get(path) != now.get(path):
            out.append(f"{label} (`{path}`): approved {_show(approved.get(path))}, now {_show(now.get(path))}")
    return out


def record(fi_dir: Path, cfg: Any) -> None:
    """Record ``cfg``'s settings as the approved ones (the first start, or ``--update``)."""
    fi_dir.mkdir(parents=True, exist_ok=True)
    (fi_dir / NAME).write_text(
        json.dumps({"schema": SCHEMA, "settings": settings_of(cfg)}, indent=2, sort_keys=True) + "\n", encoding="utf-8",
    )


def check(quest_root: Path, fi_dir: Path, cfg: Any) -> list[str]:
    """Compare ``cfg`` with the recorded settings and return the differences (empty: go on).

    With nothing recorded yet: an interview-written config (``quest_root/config.yaml`` starts with the interview's
    header) is recorded now, as it was approved on the confirm screen; any other config is left unrecorded. A record
    that cannot be read is treated as missing and written again, never as a difference."""
    path = fi_dir / NAME
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        approved = data["settings"] if data.get("schema") == SCHEMA else None
    except (OSError, ValueError, KeyError, TypeError, AttributeError):
        approved = None
    if not isinstance(approved, dict):
        try:
            written_by_interview = (quest_root / "config.yaml").read_text(encoding="utf-8").startswith(INTERVIEW_MARK)
        except OSError:
            written_by_interview = False
        if written_by_interview:
            record(fi_dir, cfg)
        return []
    return differences(approved, settings_of(cfg))
