"""Pre-quest planning proposal.

Inverts the usual flow. Instead of: type a topic → run the full quest
loop → see the paper → realize the question was poorly scoped → throw
away the result, the user runs ``/proposal "<topic>"`` first to get a
1-page LLM-written planning doc (background, hypothesis, plan, risks,
success criteria) for review BEFORE committing compute to the full
quest. If the proposal looks good, the user runs the auto-generated
YAML at ``outputs/_drafts/<slug>.yaml`` to start the actual quest.

CLI:    ``python launch.py --proposal "<topic string>"``
VSCode: ``@fi /proposal <topic string>``

Design decisions for v1
=======================

* **Two outputs**, not one: the markdown (`<slug>-proposal.md`) is
  the human-readable planning doc; the YAML (`<slug>.yaml`) is a
  minimal-but-complete config ready to feed into ``/start``. The
  YAML's ``topic:`` field is the **user's original** topic string,
  not the LLM's expansion — the quest engine should start fresh
  from the user's intent, the proposal is just the "is this worth
  running?" gate.
* **No new LangGraph node.** The plan considered inserting a
  ``propose`` node before clarify in the engine; deferred to v2.
  For v1 the proposal is a standalone pre-quest utility — keeps the
  LangGraph stable and ``/proposal`` independently shippable.
* **Drafts dir, not a quest dir.** Output lands in
  ``outputs/_drafts/`` so proposals don't pollute the quest listing
  in ``/resume``. Once the user kicks off the quest from the YAML,
  the real quest dir is created normally.

Reuses ``core.digest`` quest-id helpers indirectly via ``_slugify``;
otherwise standalone.
"""

from __future__ import annotations

import logging
import re
import string
import time
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .config import ProviderConfig
from .knowledge import Knowledge
from .provider import (
    LLMClient,
    PROXY_PROVIDERS,
    ProxySupervisor,
    resolve_endpoint_async,
)

_log = logging.getLogger("frontier_insight.proposal")

PROMPT_PATH = Path(__file__).resolve().parent.parent / "agents" / "proposal.md"

# Max topic length we accept. Real research topics are 1-3 paragraphs;
# 4000 chars is comfortable for that. Anything over that is probably
# a paste-of-an-entire-paper situation and we refuse.
_MAX_TOPIC_CHARS = 4_000


@dataclass
class ProposalArtifacts:
    """What :func:`generate_proposal` returns."""

    proposal_id: str
    proposal_path: Path        # the human-readable planning markdown
    yaml_path: Path            # the auto-generated minimal config.yaml
    ingested_to_axon: bool
    raw_state: dict[str, Any] = field(default_factory=dict)


# ---------- slug + id generation -------------------------------------------


def _slugify_topic(topic: str, *, max_chars: int = 48) -> str:
    """Filesystem-safe slug derived from the topic's first words.
    Mirrors the slug shape used elsewhere (``core/engine.py``'s quest_id
    generator) so a proposal's slug visually matches the quest_id the
    eventual quest will get."""
    # Take the first N alphanumeric-ish words.
    cleaned = re.sub(r"[^a-z0-9\s-]+", "", topic.lower())
    cleaned = re.sub(r"\s+", "-", cleaned).strip("-")
    if not cleaned:
        return "proposal"
    return cleaned[:max_chars].rstrip("-") or "proposal"


def _new_proposal_id(topic: str) -> str:
    """Stable-prefix unique id. The epoch makes proposals sortable by
    creation time; the slug keeps the filename grep-able; the 6-hex
    nonce prevents collisions when the user runs /proposal twice on
    the same topic within one second."""
    slug = _slugify_topic(topic)
    return f"{int(time.time())}-{slug}-{uuid.uuid4().hex[:6]}"


# ---------- prompt rendering ------------------------------------------------


def _build_proposal_prompt(topic: str, *, generated_at: datetime) -> str:
    """Plug the user's topic into the proposal prompt template."""
    template = string.Template(PROMPT_PATH.read_text(encoding="utf-8"))
    return template.substitute(
        topic=topic.strip(),
        generated_at=generated_at.date().isoformat(),
    )


# ---------- YAML emission ---------------------------------------------------


_DEFAULT_YAML_TEMPLATE = """\
# Auto-generated by `@fi /proposal` on ${generated_at}.
# Companion planning doc: ${proposal_filename}
#
# To run this quest:
#   python launch.py --config ${yaml_filename}
# or:
#   @fi /start ${yaml_filename}

topic: |
${indented_topic}

title: ${title}

provider:
  name: vscode_extension
  model: gpt-5

execution:
  sandbox: venv
  timeout_s: 600

knowledge:
  enabled: true
  # Pin the planning doc this YAML was generated from so the quest
  # engine reads it verbatim (not just via probabilistic Axon
  # retrieval). Forces the design + write nodes to honour the
  # hypothesis / success criteria / scope limits already approved
  # in the proposal.
  local_papers:
    - ${proposal_path}

output:
  kinds: [paper_md, paper_pdf]
  output_dir: ./outputs
"""


def _render_companion_yaml(
    topic: str, *, proposal_id: str, generated_at: datetime,
    proposal_path: Path | None = None,
) -> str:
    """Build the minimal YAML companion. ``topic:`` carries the user's
    ORIGINAL string verbatim (the LLM's expansion stays in the .md
    file); the quest engine starts fresh from the user's intent.

    ``proposal_path`` is the absolute path of the just-written
    planning markdown; we render it under ``knowledge.local_papers``
    so the quest engine pins the proposal at the head of literature
    retrieval. Absolute (not relative) so the YAML survives being
    moved before ``/start``."""
    # Indent every line of the topic by 2 spaces so the YAML's `|`
    # block-scalar parses cleanly even when the topic has empty lines.
    indented = "\n".join(
        ("  " + line) if line else "  " for line in topic.strip().splitlines()
    )
    title_slug = _slugify_topic(topic, max_chars=64)
    pinned = str(proposal_path).replace("\\", "/") if proposal_path else (
        f"outputs/_drafts/{proposal_id}-proposal.md"
    )
    return string.Template(_DEFAULT_YAML_TEMPLATE).substitute(
        generated_at=generated_at.date().isoformat(),
        proposal_filename=f"{proposal_id}-proposal.md",
        yaml_filename=f"outputs/_drafts/{proposal_id}.yaml",
        indented_topic=indented,
        title=title_slug,
        proposal_path=pinned,
    )


# ---------- Axon ingest -----------------------------------------------------


def _ingest_proposal_to_axon(
    knowledge: Knowledge, *, proposal_id: str, markdown: str,
    topic: str,
) -> bool:
    try:
        return bool(knowledge.add_text(
            text=markdown,
            kind="fi_proposal",
            metadata={
                "proposal_id": proposal_id,
                "topic": topic[:400],   # truncated for metadata sanity
            },
        ))
    except Exception as e:
        _log.warning("proposal Axon ingest failed: %r", e)
        return False


# ---------- top-level -------------------------------------------------------


async def generate_proposal(
    topic: str,
    outputs_dir: Path,
    *,
    provider: ProviderConfig,
    supervisor: ProxySupervisor | None = None,
    knowledge: Knowledge | None = None,
    now: datetime | None = None,
) -> ProposalArtifacts:
    """Produce a pre-quest proposal markdown + companion YAML.

    Raises ``ValueError`` for empty or oversized topics. Lets LLM /
    network errors bubble up. Writes both files atomically (the .md
    first; .yaml only after the .md succeeds) so a crash mid-LLM
    leaves no half-written YAML pointing at a non-existent .md.
    """
    topic = topic.strip()
    if not topic:
        raise ValueError("--proposal: topic must be non-empty")
    if len(topic) > _MAX_TOPIC_CHARS:
        raise ValueError(
            f"--proposal: topic too long ({len(topic)} > {_MAX_TOPIC_CHARS} chars). "
            f"Save it to a .yaml's `topic:` field directly and skip the proposal pass.",
        )

    now = now or datetime.now(timezone.utc)
    outputs_dir = Path(outputs_dir).expanduser().resolve()
    drafts_dir = outputs_dir / "_drafts"
    drafts_dir.mkdir(parents=True, exist_ok=True)

    proposal_id = _new_proposal_id(topic)
    proposal_path = drafts_dir / f"{proposal_id}-proposal.md"
    yaml_path = drafts_dir / f"{proposal_id}.yaml"

    prompt = _build_proposal_prompt(topic, generated_at=now)

    own_supervisor = supervisor is None
    sup = supervisor or ProxySupervisor()
    endpoint = await resolve_endpoint_async(provider, sup)
    client = LLMClient(endpoint)
    try:
        markdown = await client.chat(
            [{"role": "user", "content": prompt}],
            # Lower than critique because the proposal should converge
            # on a single sane plan, not exploratory failure-mode
            # brainstorming.
            temperature=0.2,
            node="proposal",
        )
    finally:
        await client.aclose()
        if provider.name in PROXY_PROVIDERS:
            await sup.release(provider.name)
        if own_supervisor:
            await sup.shutdown()

    # Write the planning doc, THEN the companion YAML — order matters
    # for crash-safety: if the YAML existed but the .md didn't, the
    # user's "/start <yaml>" run would succeed but a follow-up
    # /resume picker would point at a missing proposal file.
    proposal_path.write_text(markdown.strip() + "\n", encoding="utf-8")

    yaml_text = _render_companion_yaml(
        topic, proposal_id=proposal_id, generated_at=now,
        proposal_path=proposal_path,
    )
    yaml_path.write_text(yaml_text, encoding="utf-8")

    ingested = False
    if knowledge is not None and knowledge.enabled:
        ingested = _ingest_proposal_to_axon(
            knowledge, proposal_id=proposal_id,
            markdown=markdown, topic=topic,
        )

    _log.info(
        "proposal %s: .md=%s yaml=%s ingested=%s",
        proposal_id, proposal_path, yaml_path, ingested,
    )

    return ProposalArtifacts(
        proposal_id=proposal_id,
        proposal_path=proposal_path,
        yaml_path=yaml_path,
        ingested_to_axon=ingested,
        raw_state={
            "topic": topic,
            "generated_at": now.isoformat(),
        },
    )
