"""Rebuild wiki/index.md from the pages in wiki/.

Each page is listed once as ``[[slug|Title]]``, grouped by the ``type`` in its front matter (pages without one go under
"Pages"). The title comes from the front matter ``title``, else the first ``# `` heading, else the file name.
``--check`` exits 1 when index.md is out of date or a page links to a page that does not exist, without writing.

Usage: python scripts/wiki_sync_index.py [--wiki-dir wiki] [--check]
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

SKIP = {"index.md", "log.md"}
HEADER = "# Wiki Index\n\n> Rebuilt by `scripts/wiki_sync_index.py`. Do not edit this file by hand.\n"
_FRONT = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)
# ``[[target]]``, ``[[target|label]]``, ``[[target#anchor|label]]``; inside a Markdown table the pipe is written ``\|``.
_LINK = re.compile(r"\[\[([^\]|#\\]+)(?:#[^\]|\\]*)?(?:\\?\|[^\]]*)?\]\]")
_CODE = re.compile(r"```.*?```|`[^`\n]*`", re.DOTALL)


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig").replace("\r\n", "\n")


def _meta(text: str) -> dict[str, str]:
    m = _FRONT.match(text)
    out: dict[str, str] = {}
    if m:
        for line in m.group(1).splitlines():
            if ":" in line and not line.startswith((" ", "\t", "-")):
                key, value = line.split(":", 1)
                out[key.strip()] = value.strip().strip("\"'")
    return out


def _title(path: Path, text: str, meta: dict[str, str]) -> str:
    if meta.get("title"):
        return meta["title"]
    body = _FRONT.sub("", text, count=1)
    heading = next((ln[2:].strip() for ln in body.splitlines() if ln.startswith("# ")), "")
    return heading or path.stem


def pages(wiki: Path) -> list[tuple[str, str, str]]:
    """``(slug, title, group)`` for every page, sorted by group then title."""
    out = []
    for path in sorted(wiki.glob("*.md")):
        if path.name in SKIP:
            continue
        text = _read(path)
        meta = _meta(text)
        group = meta.get("type", "").strip().lower() or "pages"
        out.append((path.stem, _title(path, text, meta), group[:1].upper() + group[1:]))
    return sorted(out, key=lambda p: (p[2], p[1].lower()))


def render(wiki: Path) -> str:
    found = pages(wiki)
    lines = [HEADER, f"> {len(found)} pages.\n"]
    group = None
    for slug, title, grp in found:
        if grp != group:
            count = sum(1 for p in found if p[2] == grp)
            lines.append(f"\n## {grp} ({count})\n\n")
            group = grp
        lines.append(f"- [[{slug}|{title}]]\n")
    return "".join(lines)


def broken_links(wiki: Path) -> list[str]:
    """``file: [[target]]`` for every wiki link whose target is not a page file (links resolve by file name). Links
    written inside code (an example in backticks) are not links."""
    slugs = {p.stem for p in wiki.glob("*.md")}
    out = []
    for path in sorted(wiki.glob("*.md")):
        for target in _LINK.findall(_CODE.sub("", _read(path))):
            if target.strip() not in slugs:
                out.append(f"{path.name}: [[{target.strip()}]]")
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--wiki-dir", default="wiki")
    ap.add_argument("--check", action="store_true", help="report, do not write; exit 1 when something is wrong")
    args = ap.parse_args(argv)
    wiki = Path(args.wiki_dir)
    index = wiki / "index.md"
    new = render(wiki)
    broken = broken_links(wiki)
    stale = not index.is_file() or _read(index) != new
    if args.check:
        for b in broken:
            print(f"broken link: {b}")
        if stale:
            print("index.md is out of date: run python scripts/wiki_sync_index.py")
        return 1 if (broken or stale) else 0
    index.write_text(new, encoding="utf-8", newline="\n")
    print(f"wrote {index} ({len(pages(wiki))} pages)")
    for b in broken:
        print(f"broken link: {b}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
