"""Subprocess pool for quests spawned from the web UI.

The ``--serve`` web UI lets the user fill out the interview form and
press "Launch" — this module spawns ``python launch.py --config <path>``
as a child process and tracks the resulting PID so the server can:

* Cap the number of concurrent quests at ``--max-concurrent``.
* Surface the running PID + start time in the dashboard.
* Send a SIGTERM (then SIGKILL after a grace period) when the user
  clicks "cancel" on the quest detail page.
* Reap zombies on a periodic sweep so a finished quest doesn't
  occupy a slot indefinitely.

Process isolation matters: a quest that hits a divide-by-zero in
the engine should NOT kill the FastAPI server. Subprocess gives us
that for free.

The launcher is intentionally minimal — no shell, no PATH games,
no env-var injection beyond what the parent server already has.
Quest IDs come straight from the engine (the mint happens
server-side after Engine() instantiation), and the YAML path is
generated by the interview submit handler, so neither value is
user-controlled at the launcher boundary.
"""

from __future__ import annotations

import os
import signal
import subprocess
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from threading import Lock
from typing import Any


@dataclass
class LaunchedQuest:
    """One row in the launcher's in-memory registry."""

    quest_id: str
    yaml_path: Path
    pid: int
    started_at: float
    process: subprocess.Popen[bytes] = field(repr=False)
    # Path to the captured stdout+stderr log. Lets the UI surface
    # "the install actually crashed at step N" instead of just
    # "started" forever.
    log_path: Path | None = None

    def is_alive(self) -> bool:
        """Return True iff the OS reports the process still running.
        ``poll()`` returns None while the child is alive and an
        exit code once it's reaped. We don't keep the exit code
        because the engine already writes it into run.log."""
        return self.process.poll() is None

    def age_seconds(self) -> float:
        return max(0.0, time.time() - self.started_at)


class QuestLauncher:
    """Bounded-concurrency launcher backed by a list of
    :class:`LaunchedQuest`. Thread-safe via a Lock; the FastAPI
    handlers may invoke it from any worker thread.

    The pool does NOT block when at capacity — it raises
    :class:`QuestLauncherFull` so the handler can return a 503 and
    let the user retry. Queueing inside the launcher would hold an
    HTTP connection open potentially for hours, which is worse than
    surfacing the cap to the client.
    """

    def __init__(
        self,
        repo_root: Path,
        max_concurrent: int = 4,
        *,
        python_path: str | None = None,
        vscode_bridge_port: int = 0,
        vscode_bridge_socket: str = "",
    ) -> None:
        self.repo_root = repo_root.resolve()
        self.max_concurrent = max_concurrent
        self.python_path = python_path or sys.executable
        self.vscode_bridge_port = vscode_bridge_port
        self.vscode_bridge_socket = vscode_bridge_socket
        self._quests: list[LaunchedQuest] = []
        self._lock = Lock()

    def launch(self, *, quest_id: str, yaml_path: Path) -> LaunchedQuest:
        """Spawn ``python launch.py --config <yaml_path>`` and record
        the resulting :class:`LaunchedQuest`. Raises
        :class:`QuestLauncherFull` when the pool is at
        ``max_concurrent`` after reaping any finished children.
        """
        self._reap_finished()
        with self._lock:
            alive = sum(1 for q in self._quests if q.is_alive())
            if alive >= self.max_concurrent:
                raise QuestLauncherFull(
                    f"already running {alive} quest(s); cap is "
                    f"{self.max_concurrent}. Wait for one to finish "
                    f"or raise --max-concurrent."
                )
            argv = [
                self.python_path, "-u",
                str(self.repo_root / "launch.py"),
                "--config", str(yaml_path),
            ]
            if self.vscode_bridge_port > 0:
                argv.extend(["--vscode-bridge-port", str(self.vscode_bridge_port)])
            if self.vscode_bridge_socket:
                argv.extend(["--vscode-bridge-socket", self.vscode_bridge_socket])
            # PYTHONUNBUFFERED + -u so the engine's logs flush to the
            # quest's run.log promptly (the UI reads from that file,
            # not the subprocess stdout).
            # FI_PRESEED_QUEST_ID pins the child Engine's quest_id to
            # the one the caller already minted, so the submit handler
            # can return /quest/<id> with a stable redirect target
            # before the child even reaches Engine.__init__.
            env = {
                **os.environ,
                "PYTHONUNBUFFERED": "1",
                "FI_PRESEED_QUEST_ID": quest_id,
            }
            # Capture the child's stdout + stderr to a file under
            # outputs/_logs/ so a silent failure (e.g. tectonic
            # install crashing on a network error) is investigatable.
            # Previously stdout/stderr were redirected to DEVNULL,
            # which gave the UI no way to surface "the install
            # actually failed" — the user saw "started" forever.
            from datetime import datetime
            logs_dir = self.repo_root / "outputs" / "_logs"
            logs_dir.mkdir(parents=True, exist_ok=True)
            log_path = logs_dir / f"{quest_id}.log"
            log_file = open(log_path, "wb")
            proc = subprocess.Popen(
                argv,
                cwd=str(self.repo_root),
                env=env,
                stdout=log_file,
                stderr=subprocess.STDOUT,
                # detach the child so a server SIGINT doesn't cascade
                # — quests should keep running until they finish (or
                # are explicitly canceled). On POSIX, start_new_session
                # gives a new process group. On Windows, the equivalent
                # is CREATE_NEW_PROCESS_GROUP.
                start_new_session=(os.name != "nt"),
                creationflags=(
                    getattr(subprocess, "CREATE_NEW_PROCESS_GROUP", 0)
                    if os.name == "nt" else 0
                ),
            )
            entry = LaunchedQuest(
                quest_id=quest_id,
                yaml_path=yaml_path,
                pid=proc.pid,
                started_at=time.time(),
                process=proc,
                log_path=log_path,
            )
            self._quests.append(entry)
            return entry

    def cancel(self, quest_id: str, *, grace_s: float = 5.0) -> bool:
        """Send SIGTERM to the quest's child AND its descendants;
        escalate to SIGKILL after ``grace_s`` seconds. Returns True
        if a process was signaled, False if the quest_id isn't
        tracked or already exited.

        The engine spawns experiment scripts (and venv-managed
        subprocesses) as grandchildren of the launch.py child. A
        plain ``Popen.terminate()`` only signals the direct child;
        grandchildren are reparented to init and survive. On POSIX
        we signal the whole process group (``os.killpg`` against the
        new session created by ``start_new_session=True`` in
        ``launch``). On Windows we use ``CTRL_BREAK_EVENT`` against
        the process group created by ``CREATE_NEW_PROCESS_GROUP`` —
        same effect."""
        with self._lock:
            target = next(
                (q for q in self._quests if q.quest_id == quest_id), None,
            )
        if target is None or not target.is_alive():
            return False
        try:
            if os.name == "nt":
                # CTRL_BREAK_EVENT delivers to the whole process
                # group created at spawn time.
                target.process.send_signal(signal.CTRL_BREAK_EVENT)
            else:
                # Signal the whole process group. The pgid equals
                # the child's pid because start_new_session=True
                # made the child a session/group leader. SIGTERM
                # the group; if the engine ignores it, the escalation
                # below sends SIGKILL.
                try:
                    os.killpg(target.pid, signal.SIGTERM)
                except (ProcessLookupError, PermissionError):
                    # Group already gone or restricted — fall back
                    # to the direct child.
                    target.process.terminate()
        except (ProcessLookupError, OSError):
            return False
        # Wait briefly for cooperative shutdown.
        try:
            target.process.wait(timeout=grace_s)
            return True
        except subprocess.TimeoutExpired:
            try:
                if os.name == "nt":
                    target.process.kill()
                else:
                    # SIGKILL the whole group on the escalation
                    # path too — same orphan-prevention reason.
                    try:
                        os.killpg(target.pid, signal.SIGKILL)
                    except (ProcessLookupError, PermissionError):
                        target.process.kill()
                target.process.wait(timeout=2.0)
            except (ProcessLookupError, OSError, subprocess.TimeoutExpired):
                pass
            return True

    def list_alive(self) -> list[LaunchedQuest]:
        """Snapshot of currently-running quests. Reaping happens
        as a side effect so the returned list is fresh."""
        self._reap_finished()
        with self._lock:
            return [q for q in self._quests if q.is_alive()]

    def status_for(self, quest_id: str) -> dict[str, Any] | None:
        """One quest's launcher metadata for the GUI's
        ``GET /api/quests/<id>`` response. Returns ``None`` if the
        quest was never launched through this launcher (e.g. started
        via the CLI directly).

        When the child has exited, includes ``exit_code`` so the UI
        can distinguish "still running" / "finished cleanly" /
        "crashed". For non-zero exits, also includes the tail of
        the captured subprocess log so a silent failure (e.g.
        tectonic install crashing on a network error) surfaces
        instead of leaving the user staring at a perpetual
        "starting…" message."""
        with self._lock:
            entry = next(
                (q for q in self._quests if q.quest_id == quest_id), None,
            )
        if entry is None:
            return None
        alive = entry.is_alive()
        out: dict[str, Any] = {
            "pid": entry.pid,
            "started_at": entry.started_at,
            "alive": alive,
            "age_seconds": entry.age_seconds(),
        }
        if not alive:
            out["exit_code"] = entry.process.returncode
            if entry.process.returncode and entry.log_path and entry.log_path.is_file():
                try:
                    lines = entry.log_path.read_text(
                        encoding="utf-8", errors="replace",
                    ).splitlines()
                    out["log_tail"] = lines[-40:]
                except OSError:
                    pass
        return out

    def _reap_finished(self) -> None:
        """Walk the registry, drop any entry whose child has exited.
        Called from every public method so the alive-count is
        accurate without a separate sweep thread."""
        with self._lock:
            self._quests = [q for q in self._quests if q.is_alive()]


    def get_log_tail(self, quest_id: str, *, n: int = 200) -> list[str] | None:
        """Read the last ``n`` lines of the subprocess's captured
        stdout+stderr log. Returns None when the quest isn't
        tracked or no log was captured (e.g. quests launched from
        CLI directly). Used by the UI to surface install / quest
        failures that previously went to DEVNULL."""
        with self._lock:
            entry = next(
                (q for q in self._quests if q.quest_id == quest_id), None,
            )
        if entry is None or entry.log_path is None:
            return None
        if not entry.log_path.is_file():
            return None
        try:
            lines = entry.log_path.read_text(
                encoding="utf-8", errors="replace",
            ).splitlines()
            return lines[-n:]
        except OSError:
            return None

    def launch_command(
        self,
        *,
        argv_tail: list[str],
        job_id: str,
        extra_env: dict[str, str] | None = None,
    ) -> LaunchedQuest:
        """Spawn ``python launch.py <argv_tail>`` for a tool that
        doesn't produce a regular quest (e.g. ``--digest``,
        ``--portfolio``, ``--ingest``, ``--proposal``,
        ``--critique``, ``--install-tectonic``). ``job_id`` is the
        synthetic identifier the launcher tracks the subprocess
        under — typically ``"digest-<timestamp>"`` or similar.

        Same concurrency cap + reaping as :meth:`launch`. Reuses
        the LaunchedQuest tuple even though there's no quest dir;
        the front-end consults ``status_for(job_id)`` to know when
        the subprocess has finished + show a link to the produced
        artifact (under ``outputs/_digests/``, ``outputs/_drafts/``,
        etc., depending on the tool).
        """
        self._reap_finished()
        with self._lock:
            alive = sum(1 for q in self._quests if q.is_alive())
            if alive >= self.max_concurrent:
                raise QuestLauncherFull(
                    f"already running {alive} job(s); cap is "
                    f"{self.max_concurrent}. Wait for one to finish "
                    f"or raise --max-concurrent."
                )
            argv = [self.python_path, "-u", str(self.repo_root / "launch.py")]
            argv.extend(argv_tail)
            if self.vscode_bridge_port > 0 and "--vscode-bridge-port" not in argv_tail:
                argv.extend(["--vscode-bridge-port", str(self.vscode_bridge_port)])
            if self.vscode_bridge_socket and "--vscode-bridge-socket" not in argv_tail:
                argv.extend(["--vscode-bridge-socket", self.vscode_bridge_socket])
            env = {**os.environ, "PYTHONUNBUFFERED": "1"}
            if extra_env:
                env.update(extra_env)
            logs_dir = self.repo_root / "outputs" / "_logs"
            logs_dir.mkdir(parents=True, exist_ok=True)
            log_path = logs_dir / f"{job_id}.log"
            log_file = open(log_path, "wb")
            proc = subprocess.Popen(
                argv,
                cwd=str(self.repo_root),
                env=env,
                stdout=log_file,
                stderr=subprocess.STDOUT,
                start_new_session=(os.name != "nt"),
                creationflags=(
                    getattr(subprocess, "CREATE_NEW_PROCESS_GROUP", 0)
                    if os.name == "nt" else 0
                ),
            )
            # The job_id stands in for quest_id in the LaunchedQuest
            # tuple. yaml_path is the empty path — these tools don't
            # take a config file. status_for(job_id) lets the UI
            # show a spinner while the child runs.
            entry = LaunchedQuest(
                quest_id=job_id,
                yaml_path=Path(""),
                pid=proc.pid,
                started_at=time.time(),
                process=proc,
                log_path=log_path,
            )
            self._quests.append(entry)
            return entry


class QuestLauncherFull(Exception):
    """Raised when ``QuestLauncher.launch`` would exceed
    ``max_concurrent``. The HTTP handler should map this to 503
    with a Retry-After hint."""
